FROM debian:buster
RUN		apt-get update
RUN		apt-get -y install php-fpm php7.3-xml php7.3-curl php7.3-gd php7.3-mbstring php7.3-readline php7.3-bz2 php7.3-zip php7.3-json php7.3-opcache php-mysql
RUN		rm -rf /etc/php/7.3/fpm/pool.d/www.conf
COPY	./wordpress/www.conf /etc/php/7.3/fpm/pool.d/www.conf
COPY	./wordpress/inception /inception
RUN		mkdir /run/php

CMD ["sh", "/inception"]
