version: '2'

services:
    nginx:
        build: ./requirements/nginx/
        image: nginx
        restart: always
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - wpdata:/var/www/html
        networks:
            - mynet
    mariadb:
        build: ./requirements/mariadb
        image: mariadb
        restart: always
        container_name: mariadb
        volumes:
            - dbdata:/dbdata
        expose:
            - "3600"
        networks:
            - mynet
        depends_on:
            - nginx
        environment:
            MY_DB_NAME:     ${MY_DB_NAME}
            MY_DB_USER:     ${MY_DB_USER}
            MY_DB_PWD:      ${MY_DB_PWD}
            WP_ADMIN_ID:    ${WP_ADMIN_ID}
            WP_ADMIN_PW:    ${WP_ADMIN_PW}
            WP_USER_ID:     ${WP_USER_ID}
            WP_USER_PW:     ${WP_USER_PW}
    wordpress:
        build: ./requirements/wordpress
        image: wordpress
        container_name: wordpress
        volumes:
            - wpdata:/var/www/html
        restart: always
        networks:
            - mynet
        expose:
            - "9000"
        depends_on:
            - mariadb
        environment:
            MY_DB_NAME:     ${MY_DB_NAME}
            MY_DB_USER:     ${MY_DB_USER}
            MY_DB_PWD:      ${MY_DB_PWD}
networks:
    mynet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.23.0.0/16"
                  gateway: "172.23.0.1"
volumes:
    wpdata:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/jitlee/data/wpdata'
    dbdata:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/jitlee/data/dbdata'
